Action.create!([
  {session_id: 1, name: "Long tones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:15", notes: "Working on even timbre through all ranges"},
  {session_id: 1, name: "Alone Together", resource: "Oatts transcription", resource_url: nil, start_tempo: 120, stop_tempo: nil, keys: nil, time_spent: "00:35", notes: nil},
  {session_id: 1, name: "Garrett solo", resource: "Human Nature transcription", resource_url: "http://www-cs.canisius.edu/~bucheger/transcriptions/garrettparis.pdf", start_tempo: 105, stop_tempo: 120, keys: nil, time_spent: "00:30", notes: nil},
  {session_id: 2, name: "Long tones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:20", notes: nil},
  {session_id: 2, name: "All of You", resource: "Learn Jazz Standards", resource_url: "https://www.learnjazzstandards.com/pdf-viewer/?pdf=All_of_You_C_Instruments", start_tempo: 120, stop_tempo: nil, keys: "Eb major concert", time_spent: "00:20", notes: "Getting there..."},
  {session_id: 2, name: "Garrett solo", resource: "Human Nature, p. 2", resource_url: nil, start_tempo: 120, stop_tempo: 135, keys: nil, time_spent: "00:15", notes: nil},
  {session_id: 3, name: "Overtones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:20", notes: "Need to focus on tongue shape and airstream."},
  {session_id: 3, name: "Slow ii-V-Is", resource: "iReal", resource_url: nil, start_tempo: 70, stop_tempo: nil, keys: "12 keys", time_spent: "00:45", notes: nil},
  {session_id: 3, name: "Cry Me A River lick", resource: nil, resource_url: nil, start_tempo: 140, stop_tempo: nil, keys: "12 keys", time_spent: "00:15", notes: nil},
  {session_id: 4, name: "Overtones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:25", notes: nil},
  {session_id: 4, name: "Dexter lick", resource: nil, resource_url: nil, start_tempo: 120, stop_tempo: 140, keys: "C thru Eb", time_spent: "00:23", notes: nil},
  {session_id: 4, name: "Sonny transcription (You Don't Know What Love Is)", resource: "Printed (in binder)", resource_url: nil, start_tempo: 90, stop_tempo: nil, keys: nil, time_spent: "00:15", notes: nil},
  {session_id: 13, name: "kelly", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: "help"},
  {session_id: 13, name: "rtwf", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: "E", time_spent: nil, notes: nil},
  {session_id: 14, name: "hello", resource: nil, resource_url: nil, start_tempo: 145, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 14, name: "this is a test", resource: "notes", resource_url: nil, start_tempo: 222, stop_tempo: nil, keys: "E and F", time_spent: nil, notes: nil},
  {session_id: 15, name: "hello", resource: nil, resource_url: nil, start_tempo: 145, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 15, name: "this is a test", resource: "notes", resource_url: nil, start_tempo: 222, stop_tempo: nil, keys: "E and F", time_spent: nil, notes: nil},
  {session_id: 17, name: "Long tones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "20", notes: nil},
  {session_id: 17, name: "Overtones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "15", notes: nil},
  {session_id: 17, name: "Will Vinson blues solo", resource: "transcription", resource_url: nil, start_tempo: 100, stop_tempo: 120, keys: "G", time_spent: "35", notes: "Redo"},
  {session_id: 17, name: "Altered scale", resource: nil, resource_url: nil, start_tempo: 80, stop_tempo: nil, keys: "D", time_spent: "15", notes: nil},
  {session_id: 16, name: "TESTTESTTEST", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "20", notes: nil},
  {session_id: 16, name: "Will Vinson blues solo", resource: "transcription", resource_url: nil, start_tempo: 100, stop_tempo: 120, keys: "", time_spent: nil, notes: "Hello!"},
  {session_id: 16, name: "NEW ACTION", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 16, name: "Overtones", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "15", notes: ""},
  {session_id: 25, name: "My first action", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: "Good job!"},
  {session_id: 25, name: "My second action", resource: "From my head", resource_url: nil, start_tempo: 133, stop_tempo: 155, keys: "E", time_spent: nil, notes: nil},
  {session_id: 25, name: "Here goes another", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "49", notes: "we'll see"},
  {session_id: 25, name: "Last little guy", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: "F", time_spent: nil, notes: nil},
  {session_id: 29, name: "Long tones/Harmonics", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:17", notes: nil},
  {session_id: 29, name: "Action 2", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: "00:12", notes: nil},
  {session_id: 29, name: "Action 3", resource: nil, resource_url: nil, start_tempo: 145, stop_tempo: nil, keys: "F", time_spent: "2:00", notes: nil},
  {session_id: 29, name: "Action the Fourth", resource: nil, resource_url: nil, start_tempo: 150, stop_tempo: 160, keys: "12 keys", time_spent: ":09", notes: nil},
  {session_id: 32, name: "Test of Checkboxes", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: ":20", notes: "How  did it go?"},
  {session_id: 32, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 32, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 32, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 33, name: "Checkbox Test", resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: "All of  them.", time_spent: ":20", notes: "Here we go!"},
  {session_id: 33, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 33, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil},
  {session_id: 33, name: nil, resource: nil, resource_url: nil, start_tempo: nil, stop_tempo: nil, keys: nil, time_spent: nil, notes: nil}
])
ActionTag.create!([
  {action_id: 1, tag_id: 1},
  {action_id: 2, tag_id: 4},
  {action_id: 3, tag_id: 5},
  {action_id: 3, tag_id: 2},
  {action_id: 4, tag_id: 1},
  {action_id: 5, tag_id: 4},
  {action_id: 6, tag_id: 5},
  {action_id: 9, tag_id: 5},
  {action_id: 7, tag_id: 1},
  {action_id: 7, tag_id: 9},
  {action_id: 8, tag_id: 5},
  {action_id: 10, tag_id: 1},
  {action_id: 11, tag_id: 5},
  {action_id: 12, tag_id: 5},
  {action_id: 11, tag_id: 2},
  {action_id: 20, tag_id: 4},
  {action_id: 21, tag_id: 5},
  {action_id: 21, tag_id: 7},
  {action_id: 21, tag_id: 2},
  {action_id: 21, tag_id: 8},
  {action_id: 26, tag_id: 1},
  {action_id: 27, tag_id: 9},
  {action_id: 27, tag_id: 1},
  {action_id: 28, tag_id: 2},
  {action_id: 28, tag_id: 5},
  {action_id: 22, tag_id: 1},
  {action_id: 22, tag_id: 2},
  {action_id: 22, tag_id: 3},
  {action_id: 22, tag_id: 4},
  {action_id: 22, tag_id: 5},
  {action_id: 22, tag_id: 6},
  {action_id: 22, tag_id: 7},
  {action_id: 23, tag_id: 9},
  {action_id: 23, tag_id: 1},
  {action_id: 70, tag_id: 1},
  {action_id: 18, tag_id: 4},
  {action_id: 19, tag_id: 5},
  {action_id: 19, tag_id: 7},
  {action_id: 19, tag_id: 2},
  {action_id: 19, tag_id: 8},
  {action_id: 58, tag_id: 1},
  {action_id: 59, tag_id: 3},
  {action_id: 59, tag_id: 4},
  {action_id: 59, tag_id: 8},
  {action_id: 60, tag_id: 2},
  {action_id: 61, tag_id: 10},
  {action_id: 74, tag_id: 1},
  {action_id: 74, tag_id: 9},
  {action_id: 75, tag_id: 2},
  {action_id: 76, tag_id: 2},
  {action_id: 76, tag_id: 6},
  {action_id: 77, tag_id: 2},
  {action_id: 90, tag_id: 1}
])
Session.create!([
  {user_id: 1, date: "2019-06-12", start_notes: "Alto. Using new Berg. JS3 Reeds", start_time: nil, stop_time: nil, stop_notes: "Good session. Fatigue toward end. Work on staying loose."},
  {user_id: 1, date: "2019-06-13", start_notes: "Tenor. Tenney Berg. Trying Vandoren Jazz 2.5 reeds", start_time: nil, stop_time: nil, stop_notes: "Reeds started great, felt dead quickly."},
  {user_id: 2, date: "2019-06-12", start_notes: "Alto. Blue 1", start_time: nil, stop_time: nil, stop_notes: "Good session at the end  of a long day."},
  {user_id: 2, date: "2019-06-14", start_notes: "Alto. Blue 1", start_time: nil, stop_time: nil, stop_notes: "Blue 1 almost played out."},
  {user_id: 3, date: "2019-07-09", start_notes: "start notes are here", start_time: "2019-07-09 04:00:00", stop_time: "2019-07-09 06:00:00", stop_notes: "stop notes are here"},
  {user_id: 3, date: "2019-07-09", start_notes: "start notes are here", start_time: "2019-07-09 04:00:00", stop_time: "2019-07-09 06:00:00", stop_notes: "stop notes are here"},
  {user_id: 1, date: "2019-07-01", start_notes: "test", start_time: nil, stop_time: nil, stop_notes: nil},
  {user_id: 3, date: "2009-05-05", start_notes: "hello", start_time: nil, stop_time: nil, stop_notes: ""},
  {user_id: 3, date: "1969-05-05", start_notes: "START NOTES", start_time: nil, stop_time: nil, stop_notes: "stop notes"},
  {user_id: 3, date: "2019-07-11", start_notes: "Starting a new session", start_time: nil, stop_time: nil, stop_notes: "Good fake session"},
  {user_id: 3, date: "2019-07-12", start_notes: "Alto, reed B3.\nTrying my new Berg.", start_time: "2019-07-12 10:00:00", stop_time: "2019-07-12 13:00:00", stop_notes: "Good session. The Berg is a good piece."},
  {user_id: 3, date: "2019-07-11", start_notes: "TESTTESTSETSTEST", start_time: nil, stop_time: nil, stop_notes: ""},
  {user_id: 3, date: "2009-09-29", start_notes: "START NOTES", start_time: nil, stop_time: nil, stop_notes: "stop notes"},
  {user_id: 3, date: "2020-01-01", start_notes: "This is a test", start_time: "2019-07-15 14:00:00", stop_time: "2019-07-15 18:00:00", stop_notes: "Went well"},
  {user_id: 3, date: "2019-07-16", start_notes: "A new day.", start_time: "2019-07-15 09:00:00", stop_time: "2019-07-15 11:00:00", stop_notes: "Bye"},
  {user_id: 3, date: "2019-07-17", start_notes: "Let's see what happens", start_time: "2019-07-17 09:00:00", stop_time: "2019-07-17 11:00:00", stop_notes: "Let's  see what happened."},
  {user_id: 3, date: "2021-09-09", start_notes: "Try this again.", start_time: "2019-07-17 10:00:00", stop_time: nil, stop_notes: ""}
])
Tag.create!([
  {name: "tone"},
  {name: "range"},
  {name: "vocabulary"},
  {name: "improvisation"},
  {name: "speed"},
  {name: "rhythm"},
  {name: "other"},
  {name: "scales"},
  {name: "repertoire"},
  {name: "technique"}
])
User.create!([
  {email: "john@mail.com", name: "John", password_digest: "asdf"},
  {email: "mary@mail.com", name: "Mary", password_digest: "43rt"},
  {email: "kelly@email.com", name: "Test 1", password_digest: "$2a$12$SmChgHtHijdFVvfJB1hgEO2cwIL7ZBBZPK/TQv5ZHPdH5Nmj0KjsW"},
  {email: "test@email.com", name: "Brand", password_digest: "$2a$12$koSkx4XuRTmEuJUvFr8ejORf0yhM4MU/GEqHv11Rgzqgstm3x5UUi"},
  {email: "newuser@email.com", name: "New User", password_digest: "$2a$12$SOquGmjuQuCXd7zW0hdMGuvqg3Ve32OrMUwo.2efupm.yREnbv0aK"}
])
