json.id action.id
json.name action.name
json.session_id action.session_id
json.resource action.resource
json.resource_url action.resource_url
json.start_tempo action.start_tempo
json.stop_tempo action.stop_tempo
json.keys action.keys
json.time_spent action.time_spent
json.notes action.notes
